version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: node-app
    container_name: myapp-node-server
    command: npm start
    volumes:
      - ./backend/:/backend/
      - /backend/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react-app
    container_name: myapp-react-client
    command: npm run dev
    volumes:
      - ./frontend/:/src/
      - /node_modules
    depends_on:
      - server
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
